name: mini-jame-271_whimsy
run-name: ${{github.actor}} is running the main workflow.
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
      
jobs:
  build-game:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Get emsdk
        uses: emscripten-core/setup-emsdk@v15
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Setup project
        run: emcmake cmake -B build -S .
      - name: Build Project
        run: cmake --build build
      - name: Zip up contents
        uses: montudor/action-zip@v1
        with:
          args: zip -r game.zip build/src
      - name: Release Game
        uses: softprops/action-gh-release@v3
        with:
          files: game.zip
