name: mini-jame-271_whimsy
run-name: ${{github.actor}} is running the main workflow.
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
      
jobs:
  build-game:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Get emsdk
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: 6.0.6
          actions-cache-folder: 'emsdk-cache'

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup project
        run: emcmake cmake -B build -S .
      - name: Build Project
        run: cmake --build build

      - name: Install Zip
        uses: montudor/action-zip@v1

      - name: Zip up game folder
        run: zip -r game.zip .
        working-directory: build/src

      - name: Push to itchio
        uses: Ayowel/butler-to-itch@v2
        with:
          butler_key: ${{ secrets.BUTLER_KEY }}
          itch_user: mrpewpew
          itch_game: whimsys-garden
          version: ${{ github.ref_name }}
          files: web build/src/game.zip


      - name: Release Game
        uses: softprops/action-gh-release@v3
        with:
          files: build/src/game.zip
